import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Prateek Shukla",
      email: "prateekshukla978@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Suraj Shukla",
      email: "suraj@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: "1",
      name: "iPhone 13",
      slug: "iPhone-13",
      category: "Mobile",
      image: "/images/img1.jpg",
      brand: "apple",
      description: "best camera phone",
      price: 79000,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      // _id: "2",
      name: "iPhone 12",
      slug: "iPhone-12",
      category: "Mobile",
      image: "/images/img2.jpg",
      brand: "apple",
      description: "best camera phone",
      price: 79000,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      // _id: "3",
      name: "iPhone 11",
      slug: "iPhone-11",
      category: "Mobile",
      image: "/images/img1.jpg",
      brand: "apple",
      description: "best camera phone",
      price: 79000,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      // _id: "4",
      name: "iPhone XR",
      slug: "iPhone-XR",
      category: "Mobile",
      image: "/images/img2.jpg",
      brand: "apple",
      description: "best camera phone",
      numReviews: 10,
      price: 79000,
      countInStock: 10,
      rating: 4.5,
    },
    {
      // _id: "4",
      name: "iPhone 7",
      slug: "iPhone-7",
      category: "Mobile",
      image: "/images/img1.jpg",
      brand: "apple",
      description: "best camera phone",
      numReviews: 10,
      price: 32000,
      countInStock: 10,
      rating: 4.5,
    },
  ],
};

export default data;
