const data = {
  products: [
    {
      _id: "1",
      name: "iPhone 13",
      slug: "iPhone-13",
      category: "Mobile",
      image: "/images/img1.jpg",
      price: 79000,
      countInStock: 10,
      brand: "apple",
      rating: 4.5,
      numReviews: 10,
      description: "best camera phone",
    },
    {
      _id: "2",
      name: "iPhone 12",
      slug: "iPhone-12",
      category: "Mobile",
      image: "/images/img2.jpg",
      price: 79000,
      countInStock: 10,
      brand: "apple",
      rating: 4.5,
      numReviews: 10,
      description: "best camera phone",
    },
    {
      _id: "3",
      name: "iPhone 11",
      slug: "iPhone-11",
      category: "Mobile",
      image: "/images/img1.jpg",
      price: 79000,
      countInStock: 10,
      brand: "apple",
      rating: 4.5,
      numReviews: 10,
      description: "best camera phone",
    },
    {
      _id: "4",
      name: "iPhone XR",
      slug: "iPhone-XR",
      category: "Mobile",
      image: "/images/img2.jpg",
      price: 79000,
      countInStock: 10,
      brand: "apple",
      rating: 4.5,
      numReviews: 10,
      description: "best camera phone",
    },
  ],
};

export default data;
